### ISSUE TITLE
Grammatical edit suggestions

### ISSUE THREAD

**Issue by lynnbendixsen** [trustoverip/egf-vlei-review#12]
### Section Name

All

### Line number

6-end

### Question/Comment

Not sure if this is what you meant by "review", but hopefully you find the following list of suggested editorial comments useful.
Line # -  suggestion
Footer - all footers show 2020, should be 2021.  
6 - "requires" should be "require"
38 - Should probably specify what "the GF" refers to here.  Perhaps earlier in the document when "Governance Framework" (or longer version) is spelled out, add a trailing "(GF)" so that you can use GF later and know what it means?
42 - This "For Policies used in ToIP Governance Frameworks, the standard terminology is RFC 2119 keywords" seems passive and thus a bit vague.  suggest reword to something like "The Policies used in this document will use the standard terminology detailed in RFC2119 keywords."
59 -   "other" should be "another"
88 - missing end paren at the end of the line
89 - missing end paren at the end of the line
92 - replace period at  end of line with a semicolon
94 - add semicolon at end of line
96 - add semicolon at end of line
104 - "processes and rules which is managed separately by GLEIF with its own specification" did you mean to say something like "processes and rules _category_"?  if not adjust the plurality  of the verbs in the rest of the sentence.
157 - replace semicolon at  end of line with period.
171 - the word "in" should be "using"
203 - "and broadly useful as possible"should maybe read "and **as** broadly useful as possible"
220 - Member should be Members
285 - in extensions, either 1. is non-specific, or it contradicts 2.  It t appears that 1. states that there is no need for extensions, then 2. lists some extensions.
308 -  remove the word 'to' from "issued to by a  ..."
318 - "Enity" should be "Entity"
323 -  "included in the Appendix 5 to the vLEI Issuer Qualification Agreement' should be " included in Appendix 5 of the vLEI Issuer Qualification Agreement"
343 - the dash at the beginning of this line is confusing.  Perhaps you meant to have a heading here ?  (Controlled documents schedule?) Or a brief explanation? ("The following applies to the list of controlled documents"?) and then to be consistent with the rest of the document, change the dashes to bullets on this line and on 345)
351 - Change this line to be "A document that lists and defines _important_ terms that have been referenced in the vLEI EGF documents."  (change "important" to a better word if you have one)
422 - add a period at the end of the line.
430 -  Remove the redundant " as Appendix 5 to the vLEI Issuer Qualification Agreement"
432 - this line and the following line appear to be out of place.  Move these 2 lines to after all appendices?
447 - "useof"  should be "use of"

Apologies if any or all of this has already been reported.  Also, if this kind of review is desirable for the other documents up for review at this time, please let me know at lynn@indicio.tech and I will begin working on them also.

**Comment by kmckenna-gleif** [comment]
Thank you Lynn for your comprehensive review of the vLEI EGF Primary Document.  Please find your comments addressed below:
vLEI EGF Comments Primary Document ToIP Review – Lynn Bendixsen


- all footers show 2020, should be 2021  GLEIF: footer updated

6 - "requires" should be "require" GLEIF – change made

38 - Should probably specify what "the GF" refers to here. Perhaps earlier in the document when "Governance Framework" (or longer version) is spelled out, add a trailing "(GF)" so that you can use GF later and know what it means?   
GLEIF – This language was provided by ToIP.  Updated to ‘Governance Framework’, to spell out GF

42 - This "For Policies used in ToIP Governance Frameworks, the standard terminology is RFC 2119 keywords" seems passive and thus a bit vague. suggest reword to something like "The Policies used in this document will use the standard terminology detailed in RFC2119 keywords." 
GLEIF – This also is language provided by ToIP.  Updated sentence to read: ‘The Policies used in the Governance Framwork will use the standard terminology detailed in RFC 2119 keywords.’

59 - "other" should be "another" GLEIF – change made

88 - missing end paren at the end of the line GLEIF – change made

89 - missing end paren at the end of the line GLEIF – change made

92 - replace period at end of line with a semicolon 94 - add semicolon at end of line 
GLEIF – change made

96 - add semicolon at end of line GLEIF – change made

104 - "processes and rules which is managed separately by GLEIF with its own specification" did you mean to say something like "processes and rules _category_"? if not adjust the plurality of the verbs in the rest of the sentence.   GLEIF – updated plurality of verbs

157 - replace semicolon at end of line with period. GLEIF – change made

171 - the word "in" should be "using" GLEIF – change made

203 - "and broadly useful as possible"should maybe read "and **as** broadly useful as possible" GLEIF – change made

220 - Member should be Members GLEIF – change made

285 - in extensions, either 1. is non-specific, or it contradicts 2. It t appears that 1. states that there is no need for extensions, then 2. lists some extensions. 
GLEIF - Updated to clarify that GLEIF does not see the need to specify at this time extensions from other external Governance Frameworks which would leverage the vLEI EGF.

308 - remove the word 'to' from "issued to by a ..." GLEIF – change made

318 - "Enity" should be "Entity" GLEIF – change made

323 - "included in the Appendix 5 to the vLEI Issuer Qualification Agreement' should be " included in Appendix 5 of the vLEI Issuer Qualification Agreement" GLEIF – change made

343 - the dash at the beginning of this line is confusing. Perhaps you meant to have a heading here ? (Controlled documents schedule?) Or a brief explanation? ("The following applies to the list of controlled documents"?) and then to be consistent with the rest of the document, change the dashes to bullets on this line and on 345)
GLEIF – Updated to include the introductory phrase, ‘The Schedule of Controlled Documents:’, followed by the two bullets

 351 - Change this line to be "A document that lists and defines _important_ terms that have been referenced in the vLEI EGF documents." (change "important" to a better word if you have one) 
GLEIF – Current wording is ‘A document that lists all defined terms have been referenced in the vLEI EGF documents.’

422 - add a period at the end of the line. GLEIF – change made

430 - Remove the redundant " as Appendix 5 to the vLEI Issuer Qualification Agreement" GLEIF – change made

432 - this line and the following line appear to be out of place. Move these 2 lines to after all appendices? 
GLEIF – This is the explanation of why Appendix 5 SLA is not part of the current draft of the EGF.  Readers should be made aware of that in place of Appendix 5 SLA, the vLEI Services Catalog has been provided.

447 - "useof" should be "use of" GLEIF – change made
